#app.environment=QA
#app.base-url=https://opensource-demo.orangehrmlive.com/web/index.php/auth/login
app.edge-driver-path=C:/browserdriver/Drivers_asOf-6-18-2025/Edge/msedgedriver.exe
app.environment=QA
app.base-url=https://opensource-demo.orangehrmlive.com/web/index.php/auth/login
app.api-base-url=https://jsonplaceholder.typicode.com